name: Translate README

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      # ISO Language Codes: https://cloud.google.com/translate/docs/languages
      - name: Adding README - English
        uses: dephraiim/translate-readme@main
        with:
          LANG: en
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Adding README - Chinese Simplified
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-CN
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Adding README - Hindi
        uses: dephraiim/translate-readme@main
        with:
          LANG: hi
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Adding README - Arabic
        uses: dephraiim/translate-readme@main
        with:
          LANG: ar
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Adding README - French
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
